import * as cdrom from "./cd-rom";
import * as disk from "./disk";
import * as library from "./library";
import {canRenderSSR, renderSSR} from "./ssr";

export type Assets = {
    fetch: typeof fetch;
};

export type Env = {
    DISK_BUCKET: R2Bucket;
    ASSETS: Assets;
};
const handler: ExportedHandler<Env> = {fetch: handleRequest};

export default handler;

async function handleRequest(
    request: Request,
    env: Env,
    ctx: ExecutionContext
) {
    const url = new URL(request.url);
    const path = url.pathname.slice(1).split("/");
    if (path[0] === "CD-ROM") {
        return cdrom.handleRequest(request, env.DISK_BUCKET);
    }
    if (path[0] === "Library") {
        return library.handleRequest(request, env.ASSETS);
    }
    if (path[0] === "Disk") {
        return disk.handleRequest(request, env.DISK_BUCKET, ctx);
    }

    // LOCAL PATCH: this deployment hosts a single Hotline demo, not the full
    // Infinite Mac catalog. Send every page navigation to the demo run (file
    // requests — anything with an extension or under /assets/ — pass through).
    const demoRedirect = getDemoRedirect(url);
    if (demoRedirect) {
        return new Response(null, {
            status: 302,
            headers: {
                "Cache-Control": "private, no-store",
                "Location": demoRedirect,
            },
        });
    }

    const legacyDomainRedirect = getLegacyDomainRedirect(url);
    if (legacyDomainRedirect) {
        return new Response(null, {
            status: 301,
            headers: {
                "Cache-Control": "private, no-store",
                "Location": "https://infinitemac.org" + legacyDomainRedirect,
            },
        });
    }

    if (canRenderSSR(url)) {
        const ssrResponse = await renderSSR(request, env, url);
        if (ssrResponse) {
            return applyCommonHeaders(ssrResponse, url.pathname);
        }
    }

    try {
        const assetResponse = await env.ASSETS.fetch(request);
        const {pathname} = url;
        const response = normalizeAssetResponse(assetResponse, pathname);

        // Force a MIME type from the list at
        // https://support.cloudflare.com/hc/en-us/articles/200168396 to ensure
        // that the ROM and chunks get compressed.
        // Don't do do this for intermediate ?import requests generated by Vite
        // in dev mode, they need to be a script MIME type.
        if (
            [".rom", ".hda", "pram.bin", "nvram.bin"].some(ext =>
                pathname.endsWith(ext)
            ) &&
            !url.searchParams.has("import")
        ) {
            response.headers.set("Content-Type", "multipart/mixed");
        }

        // Static content uses a content hash in the URL, so it can be cached
        // for a while (30 days).
        if (isStaticAssetPath(pathname) && response.ok) {
            response.headers.set(
                "Cache-Control",
                `max-age=${60 * 60 * 24 * 30}`
            );
        }

        return applyCommonHeaders(response, pathname);
    } catch (e) {
        console.error("Error serving asset:", e);

        const err = e as Error;
        return new Response(err.message || err.toString(), {status: 500});
    }
}

function normalizeAssetResponse(response: Response, pathname: string) {
    // The SPA fallback returns index.html with a 200 status for missing
    // files. Never allow that response to be cached under an asset URL.
    if (
        isStaticAssetPath(pathname) &&
        response.headers
            .get("Content-Type")
            ?.toLowerCase()
            .startsWith("text/html")
    ) {
        return new Response("Not found", {
            status: 404,
            headers: {
                "Cache-Control": "private, no-store",
                "Content-Type": "text/plain; charset=utf-8",
            },
        });
    }

    return new Response(response.body, response);
}

function isStaticAssetPath(pathname: string) {
    return pathname.startsWith("/assets/");
}

function applyCommonHeaders(response: Response, pathname: string) {
    response.headers.set("X-Content-Type-Options", "nosniff");
    if (pathname === "/embed") {
        response.headers.set("Cross-Origin-Resource-Policy", "cross-origin");
    } else {
        response.headers.set("X-Frame-Options", "DENY");
    }
    // Allow SharedArrayBuffer to work
    response.headers.set("Cross-Origin-Opener-Policy", "same-origin");
    response.headers.set("Cross-Origin-Embedder-Policy", "require-corp");
    // Allow the service worker to intercept all paths, even when
    // initiated from a year subpath.
    response.headers.set("Service-Worker-Allowed", "/");

    return response;
}

// LOCAL PATCH: the single run this deployment serves.
const DEMO_PATH = "/1998/Mac%20OS%208.1";

function getDemoRedirect(url: URL): string | undefined {
    const {pathname} = url;
    if (pathname === DEMO_PATH) {
        // Already on the demo page; just make sure Hotline networking is on.
        if (url.searchParams.get("hotline") === "true") {
            return undefined;
        }
        const params = new URLSearchParams(url.searchParams);
        params.set("hotline", "true");
        return `${DEMO_PATH}?${params}`;
    }
    // Page navigations: the SPA index, year/disk paths (which can contain
    // dots, e.g. "System 7.5.5"), and any other extensionless path. Anything
    // else with an extension (or under /assets/) is a file request.
    const isPage =
        pathname === "/" ||
        pathname === "/index.html" ||
        /^\/\d{4}(\/|$)/.test(pathname) ||
        (!pathname.startsWith("/assets/") && !pathname.includes("."));
    return isPage ? `${DEMO_PATH}?hotline=true` : undefined;
}

const LEGACY_DOMAINS: {[domain: string]: string} = {
    "system6.app": "/1991/System%206.0.8",
    "system7.app": "/1996/System%207.5.3",
    "kanjitalk7.app": "/1996/KanjiTalk%207.5.3",
    "macos8.app": "/1998/Mac%20OS%208.1",
    "macos9.app": "/2000/Mac%20OS%209.0.4",
};

function getLegacyDomainRedirect(url: URL): string | undefined {
    let appleTalkZone;
    let domain = url.hostname;
    const pieces = domain.split(".");
    if (pieces.length === 3) {
        appleTalkZone = pieces[0];
        domain = pieces.slice(1).join(".");
    }

    const redirectPath = LEGACY_DOMAINS[domain];
    if (!redirectPath) {
        return undefined;
    }
    const params = url.searchParams;
    if (appleTalkZone && appleTalkZone !== "www") {
        params.set("appleTalk", appleTalkZone);
    }
    let search = params.toString();
    if (search) {
        search = "?" + search;
    }
    return redirectPath + search + url.hash;
}
